/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface VerificationInterface extends utils.Interface {
  functions: {
    "hashAndStore(string)": FunctionFragment;
    "isAddressVerified()": FunctionFragment;
    "isHashVerified(string)": FunctionFragment;
    "verifiedAddresses(address)": FunctionFragment;
    "verifiedHashes(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "hashAndStore"
      | "isAddressVerified"
      | "isHashVerified"
      | "verifiedAddresses"
      | "verifiedHashes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hashAndStore",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isAddressVerified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isHashVerified",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedAddresses",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedHashes",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "hashAndStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAddressVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isHashVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedHashes",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Verification extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VerificationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    hashAndStore(
      data: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAddressVerified(overrides?: CallOverrides): Promise<[boolean]>;

    isHashVerified(
      data: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifiedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifiedHashes(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  hashAndStore(
    data: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAddressVerified(overrides?: CallOverrides): Promise<boolean>;

  isHashVerified(
    data: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifiedAddresses(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifiedHashes(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    hashAndStore(
      data: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isAddressVerified(overrides?: CallOverrides): Promise<boolean>;

    isHashVerified(
      data: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifiedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifiedHashes(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    hashAndStore(
      data: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAddressVerified(overrides?: CallOverrides): Promise<BigNumber>;

    isHashVerified(
      data: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifiedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifiedHashes(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hashAndStore(
      data: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAddressVerified(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isHashVerified(
      data: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifiedAddresses(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifiedHashes(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
