/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrimeAssets__factory } from "./PrimeAssets__factory";
export { Verification__factory } from "./Verification__factory";
